# Generated by Django 5.1.4 on 2025-01-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_api',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini')], default='openai', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
